encoding: utf-8

# SEO相关信息
title: TMaize Blog
description: TMaize的个人博客
keywords: TMaize,Blog,Java,Html,JavaScript
author: TMaize
footerText: 'Copyright © 2016 皖ICP备16016174号'

# 留言配置, 不需要的话值设置为空，同时删除 # 菜单 配置项中的留言页面
# 官网 https://www.bmob.cn
# 文档 https://bmob.github.io/hydrogen-js-sdk
# 建议自己申请一个，表结构如下
# 表名 Comment ,字段如下 
# url      String
# time     Date
# nickName String
# email    String
# content  String
# website  String
bmobApplicationId: 34f0386ac5bd50fd77fe82190af00faf
bmobRestApiKey: 6f1419c800083315432f2df7dcb503d4

# 域名配置
# baseUrl配置,如果网站部署在根目录下的目录中，请设置为 /目录名
domainUrl: 'http://blog.tmaize.net'
baseUrl: ''

# 菜单
menu:
  - title: Home
    url: /
  - title: Categories
    url: /pages/categories.html
  - title: Search
    url: /pages/search.html
  - title: Links
    url: /pages/links.html
  - title: Chat
    url: /pages/chat.html
  - title: About
    url: /pages/about.html

# 腾讯移动分析设置
# 官网 https://mta.qq.com
# 如果需要请申请自己的，sid，cid 在统计代码里找
# 不需要请设置为false，mtaSid，mtaCid置空
mta: true
mtaSid: 500581966
mtaCid: 500581972

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
exclude: ['CNAME', 'README.md', 'build-tool']
